# $FreeBSD: head/cad/fdm_materials/Makefile 550214 2020-09-26 19:53:09Z db $

PORTNAME=	fdm_materials
DISTVERSION=	4.8.0
PORTEPOCH=	1
CATEGORIES=	cad
DIST_SUBDIR=	Ultimaker

MAINTAINER=	db@FreeBSD.org
COMMENT=	FDM Material database for 3D printers

LICENSE=	AGPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	Ultimaker
GH_TAGNAME=	933c9b3
NO_ARCH=	yes
STRIP=

.include <bsd.port.mk>
