PORTNAME=	fdm_materials
PORTEPOCH=	1
DISTVERSION=	4.10.0
CATEGORIES=	cad
DIST_SUBDIR=	Ultimaker

MAINTAINER=	db@FreeBSD.org
COMMENT=	FDM Material database for 3D printers

LICENSE=	AGPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake 

USE_GITHUB=	yes
GH_ACCOUNT=	Ultimaker
NO_ARCH=	yes
STRIP=

.include <bsd.port.mk>
